package com.example.demo.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_register_auth
 *
 * @author EDZ
 * @since 2020-08-03
 */
public class RegisterAuthDO implements Serializable {
    /**
     * '自增id'
     */
    private Long id;

    /**
     * '商户id'
     */
    private Long saasId;

    /**
     * '用户id'
     */
    private String uid;

    /**
     * '注册账户的渠道类型 0：手机号 1：邮箱 2：微信相关渠道 3：QQ渠道 4：微博渠道 5：身份证 6：其他；'
     */
    private Byte channelType;

    /**
     * '渠道名称 跟channel_type对应'
     */
    private String channelName;

    /**
     * '与channelType对应，如手机号、邮箱、身份证号、微信openId等'
     */
    private String openId;

    /**
     * '对应业务方注册渠道的应用ID'
     */
    private String appId;

    /**
     * '微信unionid'
     */
    private String wxUnionId;

    /**
     * '渠道认证密码'
     */
    private String password;

    /**
     * '邀请码'
     */
    private String invitationCode;

    /**
     * '1：永久有效 2：限时有效'
     */
    private Byte isForever;

    /**
     * '账户有效开始时间'
     */
    private Date effectiveStartTime;

    /**
     * '账户有效结束时间'
     */
    private Date effectiveEndTime;

    /**
     * '注册时间'
     */
    private Date registerTime;

    /**
     * '用户来源 0用户注册 1后台导入'
     */
    private Byte sourceType;

    /**
     * '创建时间'
     */
    private Date createTime;

    /**
     * '更新时间'
     */
    private Date updateTime;

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return '自增id'
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id '自增id'
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return '商户id'
     */
    public Long getSaasId() {
        return saasId;
    }

    /**
     * @param saasId '商户id'
     */
    public void setSaasId(Long saasId) {
        this.saasId = saasId;
    }

    /**
     * @return '用户id'
     */
    public String getUid() {
        return uid;
    }

    /**
     * @param uid '用户id'
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * @return '注册账户的渠道类型 0：手机号 1：邮箱 2：微信相关渠道 3：QQ渠道 4：微博渠道 5：身份证 6：其他；'
     */
    public Byte getChannelType() {
        return channelType;
    }

    /**
     * @param channelType '注册账户的渠道类型 0：手机号 1：邮箱 2：微信相关渠道 3：QQ渠道 4：微博渠道 5：身份证 6：其他；'
     */
    public void setChannelType(Byte channelType) {
        this.channelType = channelType;
    }

    /**
     * @return '渠道名称 跟channel_type对应'
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * @param channelName '渠道名称 跟channel_type对应'
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * @return '与channelType对应，如手机号、邮箱、身份证号、微信openId等'
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * @param openId '与channelType对应，如手机号、邮箱、身份证号、微信openId等'
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * @return '对应业务方注册渠道的应用ID'
     */
    public String getAppId() {
        return appId;
    }

    /**
     * @param appId '对应业务方注册渠道的应用ID'
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * @return '微信unionid'
     */
    public String getWxUnionId() {
        return wxUnionId;
    }

    /**
     * @param wxUnionId '微信unionid'
     */
    public void setWxUnionId(String wxUnionId) {
        this.wxUnionId = wxUnionId == null ? null : wxUnionId.trim();
    }

    /**
     * @return '渠道认证密码'
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password '渠道认证密码'
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * @return '邀请码'
     */
    public String getInvitationCode() {
        return invitationCode;
    }

    /**
     * @param invitationCode '邀请码'
     */
    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode == null ? null : invitationCode.trim();
    }

    /**
     * @return '1：永久有效 2：限时有效'
     */
    public Byte getIsForever() {
        return isForever;
    }

    /**
     * @param isForever '1：永久有效 2：限时有效'
     */
    public void setIsForever(Byte isForever) {
        this.isForever = isForever;
    }

    /**
     * @return '账户有效开始时间'
     */
    public Date getEffectiveStartTime() {
        return effectiveStartTime;
    }

    /**
     * @param effectiveStartTime '账户有效开始时间'
     */
    public void setEffectiveStartTime(Date effectiveStartTime) {
        this.effectiveStartTime = effectiveStartTime;
    }

    /**
     * @return '账户有效结束时间'
     */
    public Date getEffectiveEndTime() {
        return effectiveEndTime;
    }

    /**
     * @param effectiveEndTime '账户有效结束时间'
     */
    public void setEffectiveEndTime(Date effectiveEndTime) {
        this.effectiveEndTime = effectiveEndTime;
    }

    /**
     * @return '注册时间'
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * @param registerTime '注册时间'
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * @return '用户来源 0用户注册 1后台导入'
     */
    public Byte getSourceType() {
        return sourceType;
    }

    /**
     * @param sourceType '用户来源 0用户注册 1后台导入'
     */
    public void setSourceType(Byte sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * @return '创建时间'
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime '创建时间'
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return '更新时间'
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * @param updateTime '更新时间'
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}